apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: item-test-api
  name: item-test-api
  namespace: PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-test-api
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/item-test-api: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      creationTimestamp: null
      labels:
        app: item-test-api
    spec:
      containers:
      - image: htpgsmartitemmanagement.repos.medcity.net/htpg-smart-item-search:1.0.12-pre.3edf567
        name: item-test-api
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # volumeMounts:
        # - name: item-test-api-svc
        #   mountPath: "/etc/svc-account"
        #   readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        # - name: GOOGLE_APPLICATION_CREDENTIALS
        #   value: /etc/svc-account/hca-at-cao-sa-mgmt-42a8528d1e17.json
      # volumes:
      # - name: item-test-api-svc
      #   secret:
      #     secretName: item-test-api-svc
      serviceAccountName: item-testtest-api-svc
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000