apiVersion: v1
kind: Service
metadata:
  name: item-test-api
  namespace: PLACEHOLDER
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app: item-test-api