apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - /
  


  - target:
      kind: "(Certificate|Deployment|Service|ServiceAccount)"
    path: namespace-patch.yaml
#  - target:
#      kind: Deployment
#    patch: |-
#      - op: replace
#        path: "/spec/template/spec/containers/0/env/0"
#        value:
#          name: ENV
#          value: "dev"
transformers:
  - prefix-transformer.yaml