apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: item-csr
  namespace: PLACEHOLDER
spec:
  # Secret names are always required.
  secretName: item-pem
  duration: 8760h # 365d
  renewBefore: 720h # 30d
  subject:
    organizations:
      - Healthtrust
    organizationalUnits:
      - SupplyChain
    countries:
      - us
    provinces:
      - tennessee
    localities:
      - nashville
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - item-management-web.healthtrustpg.com,
    - item-search-api.healthtrustpg.com,
    - messaging-service-api.healthtrustpg.com,
    - item-management-api.healthtrustpg.com,
    - item-save-api.healthtrustpg.com,
    - lookup-api.healthtrustpg.com,
    - item-approval-web.healthtrustpg.com,
    - file-import-api.healthtrustpg.com,
    - virus-scan-api.healthtrustpg.com,
  # Issuer references are always required.
  issuerRef:
    #name: venafi-tpp-clusterissuer
    name: cpa-selfsigned-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io