name: publish

on:
  push:
    branches:
    - main
  workflow_dispatch:
permissions: write-all
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v2
    - run: rm -f reult*.zip
    - run: mkdir test2
    - run: ls
    - name: push
      uses: actions-x/commit@v6
      with:
       token: ${{ github.token }}
       files: ${{ github.workspace }}
    - run: ls
    
    
  zip-files:
     runs-on: ubuntu-latest
     
     steps:
      
      - uses: actions/checkout@v2
      - run: ls
      - uses: vimtor/action-zip@v1
        with:
          files: ${{github.workspace}}
          dest: result-${{ github.sha }}.zip
      - name: push
        uses: actions-x/commit@v6
