name: Repository Dispatch
on:
  push:
    branches:
    - main
  workflow_dispatch:
permissions: write-all
jobs:
 trigger:
  runs-on: ubuntu-latest
  steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.PAT }}
          repository: kjs2021/maven
          event-type: my-event
          client-payload: '{"img": "4.8.0", "sha": "${{ github.sha }}"}'
  
