name: Repository Dispatch
on:
  push:
    branches:
    - main
  workflow_dispatch:
env:
  Image_name: workflow-api
  Image_version: 1.22.00
permissions: write-all
jobs:
 trigger:
  runs-on: ubuntu-latest
  steps:
      - name: updated Imagename and Image version 
        run: |
         echo  "New Image will be  ${{ env.Image_name }}:${{ env.Image_version }}"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.PAT3 }}
          repository: kjs2021/maven
          event-type: workflow_api
          client-payload: '{"img": "${{ env.Image_name }}", "sha": "${{ github.sha }}","Image_version": "${{ env.Image_version }}"}'
  
