name: publish

on:
  push:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: mkdir test2
    - run: ls
    - name: push
      uses: actions-x/commit@v6
      with:
       token: ${{ github.token }}
