name: kk Repository Dispatch
on:
  push:
    branches:
    - main
  workflow_dispatch:
env:
  Image_name: kamal
  Image_version: 6.66.66
permissions: write-all
jobs:
 trigger:
  runs-on: ubuntu-latest
  steps:
      - name: updated Imagename and Image version 
        run: |
         echo  "New Image will be  ${{ env.Image_name }}:${{ env.Image_version }}"
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v2.1.1
      #   with:
      #     token: ${{ secrets.ROLLPAT1 }}
      #     repository: kjs2021/maven
      #     event-type: kk
      #     client-payload: '{"img": "${{ env.Image_name }}", "sha": "${{ github.sha }}","Image_version": "${{ env.Image_version }}","event_type": "${{ github.event.event_type }}","event_type2": "workflow_api"}'
      - name: get-file1
        env:
         TOKEN: ${{ secrets.ROLLPAT1 }}
        run: |
         curl -H 'Authorization: token ${{ secrets.ROLLPAT1 }}' \
         -H 'Accept: application/vnd.github.v4.raw' \
         -L https://api.github.com/repos/kjs2021/maven/contents/MyFirstFolder/hello2
         
      - name: get-file
        env:
          TOKEN: ${{ secrets.ROLLPAT1 }}
        run: |
          touch VARIABLE_NAME1
          echo "$(curl -H 'Authorization: token ${{ secrets.ROLLPAT1 }}' \
          -H 'Accept: application/vnd.github.v4.raw' \
          -O \
          -L https://api.github.com/repos/kjs2021/maven/main/MyFirstFolder/hello2)" 
          # cat  VARIABLE_NAME1
          # sed '1p' VARIABLE_NAME1

      - name: get-file3
        env:
          TOKEN: ${{ secrets.ROLLPAT1 }}
        run: |
          touch VARIABLE_NAME
          echo "hello image7777 " >> VARIABLE_NAME
          echo "hello image 1" >> VARIABLE_NAME
          echo "hello image 3" >> VARIABLE_NAME
          cat  VARIABLE_NAME
          sed '1p' VARIABLE_NAME
