name: kkpush example

on:
 workflow_dispatch:
  inputs:
      revision:
        description: 'The revision to rollback to'
        required: true
 push:
    branches:
     - main

     
env:
  Image_name: kamaljeet-final
  Image_version: 1.11.66


jobs:
# current-version:
#    - name: Get latest release 
#      uses: rez0n/actions-github-release@main
#      id: node_release
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         repository: "kjs2021/maven"
#         type: "latest"
 Fail:
  runs-on: ubuntu-latest
  steps:
   - name: Invoke workflow in another repo with inputs
     id: fail
     run: lsss

 trigger:
  runs-on: ubuntu-latest
  if:  ${{ success() }}
  needs: [Fail]
  
  steps:
      - name: updated Imagename and Image version 
        run: |
         echo  "New Image will be  ${{ env.Image_name }}:${{ env.Image_version }}"
      - name: Repository Dispatch
        id: trigger-step1
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
         workflow: kk Dispatch
         repo: kjs2021/maven
         ref: main
         token: ${{ secrets.ROLLPAT }}
         inputs: '{  "Version": "${{ env.Image_version}}" }'
         wait-for-completion: true

      - name: Another step that can handle the result
        if: always()
        run: echo "Another Workflow conclusion:${{ steps.trigger-step1.outputs.workflow-conclusion }}"
 ROll:  
   runs-on: ubuntu-latest
   environment: rollback
   if:  ${{ failure() }}
   needs: [Fail]
   steps:
   - name: Invoke workflow in another repo with inputs
     id: trigger-step2
     uses: aurelien-baudet/workflow-dispatch@v2
     with:
      workflow: kk Dispatch
      repo: kjs2021/maven
      ref: main
      token: ${{ secrets.ROLLPAT }}
      inputs: '{  "Version": "${{ vars.ROLLVERSION }}" }'
      wait-for-completion: true

   - name: Another step that can handle the result
     if: always()
     run: echo "Another Workflow conclusion:${{ steps.trigger-step2.outputs.workflow-conclusion }}"
