name: push example

on:
 workflow_dispatch:
 push:
    branches:
     - Roll-back

jobs:
 Roll:
  runs-on: ubuntu-latest
  steps:
   - name: Invoke workflow in another repo with inputs
     id: trigger-step
     uses: aurelien-baudet/workflow-dispatch@v2
     with:
      workflow: Roll-back
      repo: kjs2021/maven
      ref: Roll-back
      token: ${{ secrets.PUSHROLL }}
      inputs: '{ "message": "blah blah", "debug": true }'
      wait-for-completion: true

  - name: Another step that can handle the result
    if: always()
    run: echo "Another Workflow conclusion: ${{ steps.trigger-step.outputs.workflow-conclusion }}"
