name: push example

on:
 workflow_dispatch:
  inputs:
      revision:
        description: 'The revision to rollback to'
        required: true

      branch:
        description: 'The branch that the rollback affects'
        required: true

    
 # push:
 #    branches:
 #     - Roll-back
env:
  Image_name: workflow-api
  Image_version: 1.22.00

jobs:
 Fail:
  runs-on: ubuntu-latest
  steps:
   - name: Invoke workflow in another repo with inputs
     id: fail
     run: lssss

 trigger:
  runs-on: ubuntu-latest
  if:  ${{ success() }}
  needs: [Fail]
  steps:
      - name: updated Imagename and Image version 
        run: |
         echo  "New Image will be  ${{ env.Image_name }}:${{ env.Image_version }}"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.PAT3 }}
          repository: kjs2021/maven
          event-type: workflow_api
          client-payload: '{"img": "${{ env.Image_name }}", "sha": "${{ github.sha }}","Image_version": "${{ env.Image_version }}","event_type": "${{ github.event.event_type }}","event_type2": "workflow_api"}'
  
 Roll:
  runs-on: ubuntu-latest
  if:  ${{ failure() }}
  needs: [Fail]
  steps:
   - name: Invoke workflow in another repo with inputs
     id: trigger-step
     uses: aurelien-baudet/workflow-dispatch@v2
     with:
      workflow: Roll-back
      repo: kjs2021/maven
      ref: roll-back
      token: ${{ secrets.PUSHROLL }}
      inputs: '{ "branch": "${{ github.event.inputs.branch }}", "revision": "${{ github.event.inputs.revision }}" }'
      wait-for-completion: true

   - name: Another step that can handle the result
     if: always()
     run: echo "Another Workflow conclusion:${{ steps.trigger-step.outputs.workflow-conclusion }}"
